:sectanchors:
:toc: macro
:toclevels: 2
:toc-title: Table of Content
:numbered:

= Building JAX-WS Web Services with Apache CXF

toc::[]

== Goals

* Enterprise Integration Pattern - CBR Microservice. 

== Overview

Simple spring-boot micro-service with responsibility of routing and auditing in Mongo(NoSql) DB. This mocroservice routes the notification to a queue based on the context received to another queue.

== Prerequisites

- JDK 1.8
- Apache Maven 3.2.3
- RabbitMQ
- MongoDB


=== Compile Project

. Open a Windows or Unix terminal.
. Using the `git` utility, clone this project to your local workstation.

----
mvn clean install
mvn spring-boot:run
----

=== RabbitMQ Component

The rabbitmq: component allows you produce and consume messages from RabbitMQ instances.

Maven users will need to add the following dependency to their 'pom.xml' for this component:

---xml
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-rabbitmq</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
---

==== Spring Boot Auto-Configuration
When using Spring Boot make sure to use the following Maven dependency to have support for auto configuration:

---xml
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-rabbitmq-starter</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
---

==== Using connection factory

To connect to RabbitMQ you can setup a 'ConnectionFactory' (same as with JMS) with the login details such as:

---xml
<bean id="rabbitConnectionFactory" class="com.rabbitmq.client.ConnectionFactory">
  <property name="host" value="localhost"/>
  <property name="port" value="5672"/>
  <property name="username" value="camel"/>
  <property name="password" value="bugsbunny"/>
</bean>

And then refer to the connection factory in the endpoint uri as shown below:

<camelContext>
  <route>
    <from uri="direct:rabbitMQEx2"/>
    <to uri="rabbitmq:ex2?connectionFactory=#rabbitConnectionFactory"/>
  </route>
</camelContext>
---

From Camel 2.21 onwards the ConnectionFactory is auto-detected by default, so you can just do
---xml
<camelContext>
  <route>
    <from uri="direct:rabbitMQEx2"/>
    <to uri="rabbitmq:ex2"/>
  </route>
</camelContext>
---

===== Issue when routing between exchanges (in Camel 2.20.x or older)
If you for example want to route messages from one Rabbit exchange to another as shown in the example below with foo → bar:
---java
from("rabbitmq:foo")
  .to("rabbitmq:bar")
---

Then beware that Camel will route the message to itself, eg foo → foo. So why is that? This is because the consumer that receives the message (eg from) provides the message header rabbitmq.EXCHANGE_NAME with the name of the exchange, eg foo. And when the Camel producer is sending the message to bar then the header rabbitmq.EXCHANGE_NAME will override this and instead send the message to foo.

To avoid this you need to either:
- Remove the header:
---java
from("rabbitmq:foo")
  .removeHeader("rabbitmq.EXCHANGE_NAME")
  .to("rabbitmq:bar")
---
- Or turn on bridgeEndpoint mode on the producer:
---java
from("rabbitmq:foo")
  .to("rabbitmq:bar?bridgeEndpoint=true")
---

From Camel 2.21 onwards this has been improved so you can easily route between exchanges. The header rabbitmq.EXCHANGE_NAME is not longer used by the producer to override the destination exchange. Instead a new header rabbitmq.EXCHANGE_OVERRIDE_NAME can be used to send to a different exchange. For example to send to cheese exchange you can do
---Java
from("rabbitmq:foo")
  .setHeader("rabbitmq.EXCHANGE_OVERRIDE_NAME", constant("cheese"))
  .to("rabbitmq:bar")
---
